# Generated by Django 3.2.9 on 2021-11-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(default='mp1', max_length=30)),
                ('scripts', models.TextField(default='No text')),
            ],
        ),
        migrations.CreateModel(
            name='Vtot',
            fields=[
                ('Url', models.TextField(default='', max_length=50, unique=True)),
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='pwn',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pwn',
            name='email',
        ),
        migrations.AddField(
            model_name='pwn',
            name='domainname',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pwn',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
