# Generated by Django 3.2.9 on 2021-11-10 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pwn',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pwn',
            name='email',
        ),
        migrations.AddField(
            model_name='pwn',
            name='BreachDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pwn',
            name='Description',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='pwn',
            name='Domain',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pwn',
            name='Name',
            field=models.TextField(default='', max_length=50),
        ),
    ]
