# Generated by Django 3.2.9 on 2021-11-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211110_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vtot',
            fields=[
                ('Url', models.TextField(default='', max_length=50, unique=True)),
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
