# Generated by Django 3.2.9 on 2021-11-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211129_0958'),
        ('api', '0003_vtot'),
    ]

    operations = [
    ]
